"use client";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
export class ApiError extends Error { constructor(public status: number, message: string) { super(message); this.name = "ApiError"; } }
async function request<T>(path: string, init?: RequestInit): Promise<T> { const headers = new Headers(init?.headers); if (init?.body) headers.set("content-type", "application/json"); try { const token = sessionStorage.getItem("manus-cookie"); if (token) headers.set("authorization", `Bearer ${token}`); } catch {} const response = await fetch(path, { ...init, headers, credentials: "include" }); const payload = await response.json().catch(() => null); if (!response.ok) throw new ApiError(response.status, payload?.error ?? "تعذر تنفيذ الطلب الآن."); return payload as T; }
function useApiQuery<T>(key: string, path: string, options: { enabled?: boolean; retry?: boolean; refetchOnWindowFocus?: boolean } = {}) { return useQuery<T, ApiError>({ queryKey: [key], queryFn: () => request<T>(path), retry: options.retry ?? false, refetchOnWindowFocus: options.refetchOnWindowFocus, enabled: options.enabled }); }
function useApiMutation<TInput, TResult>(path: string, method: "POST" | "PUT" | "PATCH" | "DELETE", toPath?: (input: TInput) => string) { return useMutation<TResult, ApiError, TInput>({ mutationFn: input => request<TResult>(toPath ? toPath(input) : path, { method, body: method === "DELETE" ? undefined : JSON.stringify(input) }) }); }
type AuthUser = { id: number; openId: string; name: string | null; email: string | null; role: "user" | "admin" }; type Theme = "light" | "dark" | "pink" | "purple"; type Mood = "very_low" | "low" | "neutral" | "good" | "great" | "irritable" | "anxious"; type ProfileInput = { displayName: string; averageCycleLength: number; typicalBleedingDays: number; relationshipStatus: "single" | "married"; pregnancyStatus: "not_pregnant" | "pregnant" | "not_sure"; theme: Theme; stealthMode: boolean; onboardingCompleted: boolean }; type ProfileRecord = Omit<ProfileInput, "stealthMode" | "onboardingCompleted"> & { userId: number; stealthMode: number; onboardingCompleted: number }; type CycleInput = { startDate: string; endDate: string | null; symptoms: string[]; notes: string | null }; type DailyInput = { entryDate: string; mood: Mood; painLevel: number; symptoms: string[]; notes: string | null };
export const api = { auth: { me: { useQuery: (_input: undefined, options?: { enabled?: boolean; retry?: boolean; refetchOnWindowFocus?: boolean }) => useApiQuery<AuthUser | null>("auth.me", "/api/auth/me", options) }, logout: { useMutation: () => useApiMutation<void, { success: boolean }>("/api/auth/logout", "POST") } }, profile: { get: { useQuery: (_input: undefined, options?: { enabled?: boolean }) => useApiQuery<ProfileRecord | null>("profile", "/api/profile", options) }, save: { useMutation: () => useApiMutation<ProfileInput, ProfileRecord>("/api/profile", "PUT") } }, cycles: { list: { useQuery: (_input: undefined, options?: { enabled?: boolean }) => useApiQuery<Array<CycleInput & { id: number; userId: number; symptomsJson: string }>>("cycles", "/api/cycles", options) }, create: { useMutation: () => useApiMutation<CycleInput, { id: number }>("/api/cycles", "POST") }, update: { useMutation: () => useApiMutation<CycleInput & { id: number }, { success: boolean }>("", "PATCH", input => `/api/cycles/${input.id}`) }, delete: { useMutation: () => useApiMutation<{ id: number }, { success: boolean }>("", "DELETE", input => `/api/cycles/${input.id}`) } }, dailyEntries: { list: { useQuery: (_input: undefined, options?: { enabled?: boolean }) => useApiQuery<Array<DailyInput & { id: number; userId: number; symptomsJson: string }>>("dailyEntries", "/api/daily-entries", options) }, save: { useMutation: () => useApiMutation<DailyInput, { success: boolean }>("/api/daily-entries", "POST") }, delete: { useMutation: () => useApiMutation<{ id: number }, { success: boolean }>("", "DELETE", input => `/api/daily-entries/${input.id}`) } } };
export function useApiCache() { return useQueryClient(); }
