import { Activity, ChartNoAxesCombined, HeartPulse } from "lucide-react";
import { useMemo } from "react";

type DailyEntry = { entryDate: string; mood: "very_low" | "low" | "neutral" | "good" | "great" | "irritable" | "anxious"; painLevel: number; symptoms: string[] };
const moodLabels = { very_low: "مرهقة", low: "منخفض", neutral: "متوازن", good: "جيد", great: "ممتاز", irritable: "متوترة", anxious: "قلقة" };
const moodScores = { very_low: 1, low: 2, neutral: 3, irritable: 2, anxious: 2, good: 4, great: 5 };

export function WellnessTrends({ dailyEntries }: { dailyEntries: DailyEntry[] }) {
  const entries = useMemo(() => [...dailyEntries].sort((a, b) => a.entryDate.localeCompare(b.entryDate)).slice(-14), [dailyEntries]);
  const painPoints = entries.map((entry, index) => `${entries.length === 1 ? 50 : 8 + (index / (entries.length - 1)) * 84},${78 - entry.painLevel * 15}`).join(" ");
  const moodPoints = entries.map((entry, index) => `${entries.length === 1 ? 50 : 8 + (index / (entries.length - 1)) * 84},${82 - moodScores[entry.mood] * 12}`).join(" ");
  const highPainDays = entries.filter(entry => entry.painLevel >= 3).length;
  const commonSymptom = Object.entries(entries.flatMap(entry => entry.symptoms).reduce<Record<string, number>>((counts, symptom) => ({ ...counts, [symptom]: (counts[symptom] ?? 0) + 1 }), {})).sort((a, b) => b[1] - a[1])[0];
  return <section className="surface-card page-card reference-panel trend-panel"><div className="section-header"><div><h2>اتجاهاتكِ خلال آخر 14 متابعة</h2><p>تعرض ما سجلتِه أنتِ فقط، ولا تستنتج تشخيصاً.</p></div><ChartNoAxesCombined size={21} color="var(--accent)" /></div>{entries.length < 2 ? <div className="empty-state">أضيفي متابعتين يوميتين على الأقل لتظهر الاتجاهات الشخصية.</div> : <><div className="trend-chart"><div className="trend-key"><span><i className="pain-line" />الألم</span><span><i className="mood-line" />المزاج</span></div><svg viewBox="0 0 100 90" role="img" aria-label="مخطط اتجاه الألم والمزاج"><path d="M 6 82 H 94 M 6 52 H 94 M 6 22 H 94" stroke="currentColor" opacity=".12" fill="none" /><polyline points={painPoints} fill="none" stroke="var(--accent)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /><polyline points={moodPoints} fill="none" stroke="var(--purple)" strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></svg><div className="trend-dates"><span>{entries[0]?.entryDate}</span><span>{entries.at(-1)?.entryDate}</span></div></div><div className="trend-insights"><div><HeartPulse size={16} /><span>متوسط الألم</span><strong>{(entries.reduce((sum, entry) => sum + entry.painLevel, 0) / entries.length).toFixed(1)} / 4</strong></div><div><Activity size={16} /><span>المزاج الأخير</span><strong>{moodLabels[entries.at(-1)?.mood ?? "neutral"]}</strong></div>{commonSymptom && <div><Activity size={16} /><span>الأكثر تكراراً</span><strong>{commonSymptom[0]}</strong></div>}</div>{highPainDays >= 3 && <div className="safety-callout"><HeartPulse size={17} /><span>سجلتِ ألماً مزعجاً أو شديداً في {highPainDays} أيام حديثة. هذه ملاحظة من السجل وليست تشخيصاً؛ إذا كان الألم يثير قلقكِ أو يتغير عن المعتاد، تواصلي مع مختصة.</span></div>}</>}</section>;
}
