create type public.user_role as enum ('user', 'admin');
create type public.relationship_status as enum ('single', 'married');
create type public.pregnancy_status as enum ('not_pregnant', 'pregnant', 'not_sure');
create type public.app_theme as enum ('light', 'dark', 'pink', 'purple');
create type public.mood as enum ('very_low', 'low', 'neutral', 'good', 'great', 'irritable', 'anxious');

create table public.users (
  id integer generated by default as identity primary key,
  "openId" varchar(64) not null unique,
  name text, email varchar(320), "loginMethod" varchar(64),
  role public.user_role not null default 'user',
  "createdAt" timestamptz not null default now(), "updatedAt" timestamptz not null default now(), "lastSignedIn" timestamptz not null default now()
);

create table public.user_profiles (
  id integer generated by default as identity primary key,
  user_id integer not null unique references public.users(id) on delete cascade,
  display_name varchar(80) not null, average_cycle_length integer not null default 28, typical_bleeding_days integer not null default 5,
  relationship_status public.relationship_status not null default 'single', pregnancy_status public.pregnancy_status not null default 'not_pregnant',
  theme public.app_theme not null default 'pink', stealth_mode boolean not null default false, onboarding_completed boolean not null default false,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table public.cycle_records (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  start_date varchar(10) not null, end_date varchar(10), symptoms_json text not null, notes text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index cycle_records_user_start_idx on public.cycle_records(user_id, start_date);

create table public.daily_entries (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  entry_date varchar(10) not null, mood public.mood not null, pain_level integer not null default 0 check (pain_level between 0 and 4),
  symptoms_json text not null, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique (user_id, entry_date)
);

alter table public.users enable row level security;
alter table public.user_profiles enable row level security;
alter table public.cycle_records enable row level security;
alter table public.daily_entries enable row level security;

-- The Next.js server uses DATABASE_URL and enforces userId checks in every query.
-- Keep browser access disabled until dedicated Supabase Auth policies are added.
