-- Private medication records, dose confirmations, and an optional in-app privacy lock.
alter table public.user_profiles add column if not exists app_lock_hash text;

create table if not exists public.medications (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  name varchar(120) not null,
  dosage varchar(160) not null,
  notes text,
  reminder_times_json text not null default '[]',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists medications_user_active_idx on public.medications(user_id, is_active);

create table if not exists public.medication_dose_logs (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  medication_id integer not null references public.medications(id) on delete cascade,
  dose_date varchar(10) not null,
  scheduled_time varchar(5) not null,
  taken_at timestamptz not null default now(),
  unique (user_id, medication_id, dose_date, scheduled_time)
);
create index if not exists medication_dose_logs_user_date_idx on public.medication_dose_logs(user_id, dose_date);

alter table public.medications enable row level security;
alter table public.medication_dose_logs enable row level security;

grant select, insert, update, delete on public.medications, public.medication_dose_logs to zuhiera_app;
grant usage, select on sequence public.medications_id_seq, public.medication_dose_logs_id_seq to zuhiera_app;

drop policy if exists zuhiera_app_server_access_medications on public.medications;
create policy zuhiera_app_server_access_medications on public.medications for all to zuhiera_app using (true) with check (true);

drop policy if exists zuhiera_app_server_access_medication_dose_logs on public.medication_dose_logs;
create policy zuhiera_app_server_access_medication_dose_logs on public.medication_dose_logs for all to zuhiera_app using (true) with check (true);
