create table if not exists public.password_reset_tokens (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  token_hash varchar(64) not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists password_reset_tokens_user_id_idx on public.password_reset_tokens (user_id);
create index if not exists password_reset_tokens_expires_at_idx on public.password_reset_tokens (expires_at);
alter table public.password_reset_tokens enable row level security;
create policy "password_reset_tokens_no_direct_access" on public.password_reset_tokens for all using (false) with check (false);
grant select, insert, update, delete on table public.password_reset_tokens to zuhiera_app;
grant usage, select on sequence public.password_reset_tokens_id_seq to zuhiera_app;

create table if not exists public.health_integration_consents (
  id integer generated by default as identity primary key,
  user_id integer not null references public.users(id) on delete cascade,
  platform varchar(32) not null,
  scopes_json text not null,
  consented_at timestamptz not null default now(),
  revoked_at timestamptz,
  deleted_at timestamptz,
  constraint health_integration_consents_user_platform_unique unique (user_id, platform)
);

alter table public.health_integration_consents enable row level security;
create policy "health_integration_consents_no_direct_access" on public.health_integration_consents for all using (false) with check (false);
grant select, insert, update, delete on table public.health_integration_consents to zuhiera_app;
grant usage, select on sequence public.health_integration_consents_id_seq to zuhiera_app;
